//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yt_dlp_GUI_dotnet8 {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yt_dlp_GUI_dotnet8.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   URLを追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string addURl {
            get {
                return ResourceManager.GetString("addURl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したオーディオコーディックを強制する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Audio_force {
            get {
                return ResourceManager.GetString("Audio_force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声のみダウンロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Audio_only {
            get {
                return ResourceManager.GetString("Audio_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DLリストに追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Browser_DLList {
            get {
                return ResourceManager.GetString("Browser_DLList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したコーディックを強制する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Codec_force {
            get {
                return ResourceManager.GetString("Codec_force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YouTubeのクッキーを使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cookie_Path {
            get {
                return ResourceManager.GetString("Cookie_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URLを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Infomation_URl {
            get {
                return ResourceManager.GetString("Infomation_URl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URLを入力してください（複数可） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string inputURl {
            get {
                return ResourceManager.GetString("inputURl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string inputURl_add {
            get {
                return ResourceManager.GetString("inputURl_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここにURLを貼ってね に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string inputURl_hint {
            get {
                return ResourceManager.GetString("inputURl_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した拡張子を強制する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string kaku_force {
            get {
                return ResourceManager.GetString("kaku_force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した解像度を強制する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pixel_force {
            get {
                return ResourceManager.GetString("Pixel_force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Thumb {
            get {
                return ResourceManager.GetString("Thumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yt-dlp関連の設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string yt_dlp_Settings {
            get {
                return ResourceManager.GetString("yt_dlp_Settings", resourceCulture);
            }
        }
    }
}
